### ISSUE TITLE
The language iv is not supported

### ISSUE THREAD

**Issue by tehaon** [hklemp/dotnet-stop-words#7]
I have been using your library which seems to work fine locally, but when I push it to my microsoft azure app service and try to use it I'm getting a strange error that I've not been able to debug yet. I've found no google results related to the specific "iv" language and I'm not sure where to proceed from here.

I should clarify the first part of the error the serialization exception is from my code trying to decode what was supposed to be a json result but the api returned "there was an error processing your request" which is also part of my code and then the specific exception thrown which appears to be from the stopword package.

[07/13/2020 13:25:31 > d26972: INFO] Newtonsoft.Json.JsonSerializationException: Error converting value "There was an error processing your request: System.ArgumentException: The language iv is not supported
[07/13/2020 13:25:31 > d26972: INFO]    at StopWord.StopWords.MapLanguage(String shortLanguageName)
[07/13/2020 13:25:31 > d26972: INFO]    at StopWord.StopWordsExtension.Remove(String s, String shortLanguageName)

Our specific use case is this:

```
            string sPunctRemoved = Regex.Replace(sDefn, "[^a-zA-Z0-9]+", " ");

            sFilterDefn = StopWord.StopWordsExtension.RemoveStopWords(sPunctRemoved.ToLower());
```

**Comment by tehaon** [comment]
I was able to work my way around it. I tried both Culture.CurrentCulture and Culture.InvariantCulture to no avail so I specified it manually.

```
            var cultureInfo = CultureInfo.GetCultureInfo("en-US");
            
            sFilterDefn = StopWord.StopWordsExtension.RemoveStopWords(sPunctRemoved.ToLower(), cultureInfo);
```

This appeared to fix my issue
